# backend/summary.py
"""
Grounded natural-language summary of a compound report, generated by a foundation
model (Anthropic Claude).

WHY THIS IS DESIGNED THE WAY IT IS
    An LLM that "talks about a molecule" freely is the single biggest hallucination
    risk in this whole project, and the part a pharma reviewer scrutinizes hardest.
    So this layer is deliberately NOT a chatbot. It is a *translator*: it receives
    ONLY the structured output our own models already produced (calibrated toxicity
    probabilities, the applicability-domain verdict, ADMET flags, explainability
    atoms) and is instructed to interpret those numbers in plain language — never to
    add outside chemistry knowledge and never to make clinical/therapeutic
    recommendations. That constraint is what turns it from a toy into an auditable
    explainability layer.

GOVERNANCE
    Every call returns (and appends to an audit log) the model id, a UTC timestamp,
    and SHA-256 hashes of both the exact prompt sent and the exact input report.
    That makes any past summary reproducible/auditable: given the same input hash
    and model, you can explain what was shown to the model and when.

GRACEFUL DEGRADATION
    If ANTHROPIC_API_KEY is unset or the API errors, this returns
    {available: False, reason: ...} exactly like the applicability-domain layer,
    so the /analyze experience never depends on the LLM being reachable.
"""
import hashlib
import json
import os
from datetime import datetime, timezone

# Model is env-overridable so the deployment can swap tiers without a code change.
# Haiku is plenty for a constrained summarization task and keeps cost/latency low.
SUMMARY_MODEL = os.getenv("SUMMARY_MODEL", "claude-haiku-4-5-20251001")
MAX_TOKENS = int(os.getenv("SUMMARY_MAX_TOKENS", "800"))

_AUDIT_PATH = os.path.join(os.path.dirname(__file__), "summary_audit.jsonl")

SYSTEM_PROMPT = (
    "You are a regulatory-toxicology report writer. You are given the STRUCTURED "
    "OUTPUT of an in-house machine-learning toxicity model for a single compound. "
    "Your ONLY task is to summarize and interpret the numbers you are given, in "
    "plain language, for a scientifically literate but non-specialist reader.\n\n"
    "HARD RULES:\n"
    "1. Use ONLY the data provided in the user message. Do NOT introduce chemical "
    "facts, mechanisms, toxicology, or knowledge that is not present in the input.\n"
    "2. Do NOT make clinical, dosing, therapeutic, or fitness-for-human-use "
    "recommendations of any kind.\n"
    "3. Always describe probabilities as MODEL ESTIMATES, not established facts.\n"
    "4. If the applicability-domain section reports the molecule is out of domain "
    "or low reliability, OPEN the summary with that caveat and state clearly that "
    "the predictions may be unreliable for this molecule.\n"
    "5. Be concise. Output GitHub-flavored Markdown using short sections with "
    "'###' headers. No preamble, no sign-off.\n"
)


def _fmt_report_for_prompt(report: dict) -> str:
    """Render the structured report into a compact, model-readable block.

    We hand the model a curated projection of the report (not the raw SVG or full
    atom-score vectors) so the prompt stays small and the model can't latch onto
    irrelevant fields.
    """
    tox = report.get("toxicity", {})
    toxic = {k: v for k, v in tox.items() if str(v.get("label", "")).lower() == "toxic"}
    safe_count = len(tox) - len(toxic)

    admet = report.get("admet", {})
    risk = report.get("risk_summary", {})
    ad = report.get("applicability_domain", {})
    expl = report.get("explainability", {})

    lines = []
    name = report.get("compound_name") or "(unnamed compound)"
    lines.append(f"COMPOUND: {name}")
    lines.append(f"CANONICAL SMILES: {report.get('canonical_smiles', '')}")
    lines.append("")
    lines.append("OVERALL RISK (model composite):")
    lines.append(f"  tier: {risk.get('tier')}  composite_score: {risk.get('composite_score')}")
    lines.append(f"  toxic endpoints: {len(toxic)} of {len(tox)}  ({safe_count} safe)")
    lines.append("")
    lines.append("TOXICITY ENDPOINTS FLAGGED (calibrated model probability):")
    if toxic:
        for k, v in sorted(toxic.items(), key=lambda x: -x[1].get("probability", 0)):
            lines.append(f"  {k}: {v.get('probability')} (threshold {v.get('threshold')})")
    else:
        lines.append("  none above threshold")
    lines.append("")
    lines.append("ADMET / DRUG-LIKENESS:")
    lines.append(f"  molecular_weight: {admet.get('molecular_weight')}  logP: {admet.get('logp')}")
    lines.append(f"  H-bond donors: {admet.get('hbd')}  acceptors: {admet.get('hba')}  TPSA: {admet.get('tpsa')}")
    lines.append(f"  Lipinski pass: {admet.get('lipinski_pass')}  Veber pass: {admet.get('veber_pass')}")
    pains = admet.get("pains_alerts") or []
    lines.append(f"  PAINS structural alerts: {', '.join(pains) if pains else 'none'}")
    lines.append("")
    lines.append("APPLICABILITY DOMAIN (is this molecule like the training data?):")
    if ad and ad.get("available"):
        lines.append(f"  in_domain: {ad.get('in_domain')}  reliability: {ad.get('reliability')}")
        lines.append(f"  nearest-neighbor similarity: {ad.get('max_similarity')}  "
                     f"mean-top-{ad.get('k')}: {ad.get('mean_top_k_similarity')}  "
                     f"(in-domain threshold {ad.get('threshold')})")
    else:
        reason = ad.get("reason") if isinstance(ad, dict) else None
        lines.append(f"  unavailable{f' ({reason})' if reason else ''}")
    lines.append("")
    lines.append("EXPLAINABILITY (atoms the model weighted most, by endpoint):")
    if expl:
        for endpoint, info in expl.items():
            top = info.get("top_atoms", [])
            lines.append(f"  {endpoint}: atom indices {top}")
    else:
        lines.append("  not computed")
    return "\n".join(lines)


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _write_audit(record: dict) -> None:
    """Append one governance record. Never fatal: prod should point this at durable
    storage (S3/db); on an ephemeral container the file resets on redeploy, which is
    fine for a demo as long as the *pattern* is auditable."""
    try:
        with open(_AUDIT_PATH, "a") as f:
            f.write(json.dumps(record) + "\n")
    except Exception:  # noqa: BLE001 — auditing must never break the response
        pass


def generate_summary(report: dict) -> dict:
    """Produce a grounded plain-language summary of `report`.

    Returns {available: True, markdown, governance} on success, or
    {available: False, reason} if the model is unreachable/unconfigured.
    """
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        return {"available": False, "reason": "ANTHROPIC_API_KEY not configured"}

    user_content = _fmt_report_for_prompt(report)
    prompt_hash = _sha256(SYSTEM_PROMPT + "\n----\n" + user_content)
    input_hash = _sha256(json.dumps(report, sort_keys=True, default=str))
    ts = datetime.now(timezone.utc).isoformat()

    try:
        import anthropic

        client = anthropic.Anthropic(api_key=api_key)
        resp = client.messages.create(
            model=SUMMARY_MODEL,
            max_tokens=MAX_TOKENS,
            temperature=0,  # deterministic-as-possible for reproducibility
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_content}],
        )
        markdown = "".join(
            block.text for block in resp.content if getattr(block, "type", None) == "text"
        ).strip()
        usage = getattr(resp, "usage", None)
        governance = {
            "model": SUMMARY_MODEL,
            "generated_at": ts,
            "prompt_sha256": prompt_hash,
            "input_report_sha256": input_hash,
            "temperature": 0,
            "input_tokens": getattr(usage, "input_tokens", None),
            "output_tokens": getattr(usage, "output_tokens", None),
        }
        _write_audit({**governance, "compound": report.get("compound_name") or None,
                      "canonical_smiles": report.get("canonical_smiles")})
        return {"available": True, "markdown": markdown, "governance": governance}
    except Exception as exc:  # noqa: BLE001 — LLM is advisory; never break the app
        return {"available": False, "reason": f"{type(exc).__name__}: {exc}"}
